vote:
  image:
    repository: ghcr.io/neyamatullah/vote
    tag: latest
  replicas: 1
  options:
    a: Cats
    b: Dogs
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

result:
  image:
    repository: ghcr.io/neyamatullah/result
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

worker:
  image:
    repository: ghcr.io/neyamatullah/worker
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

redis:
  image:
    repository: redis
    tag: "7-alpine"
  resources:
    limits:
      cpu: 250m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi

db:
  image:
    repository: postgres
    tag: "15-alpine"
  storage: 1Gi
  credentials:
    user: postgres
    password: postgres
    name: postgres
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

externalDb:
  enabled: false
  host: ""
  port: 5432
  user: postgres
  password: ""
  name: postgres

externalRedis:
  enabled: false
  host: ""
  port: 6379

ingress:
  host: voting.local
  className: nginx
  tls:
    enabled: false
    secretName: voting-tls

networkPolicy:
  enabled: true

sealedSecrets:
  enabled: false

vault:
  enabled: false
  role: worker
  secretPath: secret/data/voting-app/db
