---
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/voting-app

project_name: voting-app
docker_hub_username: neyamat

postgres_user: postgres
postgres_password: postgres
postgres_db: postgres
