apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
data:
  OPTION_A: {{ .Values.vote.options.a | quote }}
  OPTION_B: {{ .Values.vote.options.b | quote }}
  REDIS_HOST: {{ if .Values.externalRedis.enabled }}{{ .Values.externalRedis.host | quote }}{{ else }}"redis"{{ end }}
  REDIS_PORT: {{ if .Values.externalRedis.enabled }}{{ .Values.externalRedis.port | quote }}{{ else }}"6379"{{ end }}
  DB_HOST: {{ if .Values.externalDb.enabled }}{{ .Values.externalDb.host | quote }}{{ else }}"db"{{ end }}
  DB_NAME: {{ if .Values.externalDb.enabled }}{{ .Values.externalDb.name | quote }}{{ else }}{{ .Values.db.credentials.name | quote }}{{ end }}
